/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTfoot: typeof import('bootstrap-vue-next')['BTfoot']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BThead: typeof import('bootstrap-vue-next')['BThead']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    DisplayProduct: typeof import('./src/components/displayProduct.vue')['default']
    IMdiCart: typeof import('~icons/mdi/cart')['default']
    IMdiDrink: typeof import('~icons/mdi/drink')['default']
    IMdiFood: typeof import('~icons/mdi/food')['default']
    IMdiGa: typeof import('~icons/mdi/ga')['default']
    IMdiGal: typeof import('~icons/mdi/gal')['default']
    IMdiGallary: typeof import('~icons/mdi/gallary')['default']
    IMdiGalllary: typeof import('~icons/mdi/galllary')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    IMdiTshirt: typeof import('~icons/mdi/tshirt')['default']
    IMdiTshirtCr: typeof import('~icons/mdi/tshirt-cr')['default']
    IMdiTshirtCrew: typeof import('~icons/mdi/tshirt-crew')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
